services:
  node:
    image: opendigitaleducation/node:20-alpine-pnpm
    working_dir: /home/node/app
    environment:
      - NPM_TOKEN
      - CHROMATIC_TOKEN
    volumes:
      - ./:/home/node/app
      - ~/.pnpm:/.pnpm
