packages:
  - 'apps/*'
  - 'packages/*'
  - 'packages/**/*'

catalog:
  '@eslint/js': 9.39.2
  '@react-spring/web': 9.7.5
  '@tanstack/react-query': 5.62.7
  '@tanstack/react-query-devtools': 5.59.13
  '@testing-library/jest-dom': 6.5.0
  '@testing-library/react': 16.0.1
  '@testing-library/user-event': 14.5.2
  '@tiptap/core': 2.11.0
  '@types/node': 22.19.8
  '@types/react': 18.3.27
  '@types/react-dom': 18.3.7
  '@vitejs/plugin-react': 4.7.0
  'clsx': 2.1.1
  'eslint': 9.39.2
  'eslint-plugin-react-hooks': 5.1.0-rc.0
  'eslint-plugin-react-refresh': 0.4.26
  'globals': 15.15.0
  'i18next': 23.16.8
  'i18next-http-backend': 2.6.1
  'msw': 2.12.8
  'prettier': 3.8.1
  'react': 18.3.1
  'react-dom': 18.3.1
  'react-hook-form': 7.71.1
  'react-i18next': 14.1.3
  'rollup-plugin-pure': 0.4.0
  'rollup-plugin-visualizer': 5.12.0
  'turbo': 2.8.3
  'typescript': 5.9.3
  'typescript-eslint': 8.54.0
  'vite': 5.4.14
  'vite-plugin-dts': 4.5.4
  'vite-tsconfig-paths': 5.1.4
