import type { IGetConf, IGetSession, IUserInfo } from '@edifice.io/client';
import type { UseQueryResult } from '@tanstack/react-query';

export function mockQueryResult<T>(data: T): UseQueryResult<T> {
  return {
    data,
    isSuccess: true,
    isLoading: false,
    isPending: false,
    isError: false,
    error: null,
    status: 'success',
    fetchStatus: 'idle',
    isStale: false,
    isPlaceholderData: false,
    isFetching: false,
    isFetched: true,
    isFetchedAfterMount: true,
    isLoadingError: false,
    isRefetchError: false,
    isRefetching: false,
    dataUpdatedAt: 0,
    errorUpdatedAt: 0,
    failureCount: 0,
    failureReason: null,
    errorUpdateCount: 0,
    refetch: vi.fn() as any,
    promise: Promise.resolve(data),
  } as unknown as UseQueryResult<T>;
}

export const mockUser: IUserInfo = {
  classNames: [],
  level: '',
  login: 'user.login',
  lastName: 'Last Name',
  firstName: 'First Name',
  externalId: 'external-id',
  federated: null,
  birthDate: '2023-09-25',
  forceChangePassword: null,
  needRevalidateTerms: false,
  deletePending: false,
  username: 'user.name',
  type: 'ENSEIGNANT',
  hasPw: true,
  functions: { SUPER_ADMIN: { code: 'SUPER_ADMIN', scope: [] } },
  groupsIds: ['group-id-1'],
  federatedIDP: null,
  optionEnabled: [],
  userId: '91c22b66-ba1b-4fde-a3fe-95219cc18d4a',
  structures: ['structure-id'],
  structureNames: ['Structure Name'],
  uai: [],
  hasApp: false,
  classes: [],
  authorizedActions: [],
  apps: [],
  childrenIds: [],
  children: {},
  widgets: [],
  sessionMetadata: { _id: '', userId: '91c22b66-ba1b-4fde-a3fe-95219cc18d4a' },
};

export const mockSession: IGetSession = {
  user: mockUser,
  currentLanguage: 'fr',
  quotaAndUsage: { quota: 104857600, storage: 27683216 },
  userDescription: {
    mood: 'default',
    health: '',
    alertSize: false,
    storage: 27683216,
    type: 'USERBOOK',
    userid: '91c22b66-ba1b-4fde-a3fe-95219cc18d4a',
    picture: '/userbook/avatar/91c22b66-ba1b-4fde-a3fe-95219cc18d4a',
    quota: 104857600,
    motto: '',
    theme: 'default',
    hobbies: [],
  },
  userProfile: ['Teacher'],
  bookmarkedApps: [],
};

export const mockConf: IGetConf = {
  app: 'wiki',
  applications: [],
  conf: {
    dependencies: { themes: {}, widgets: {} },
    emitWrapper: false,
    overriding: [],
  },
  currentApp: undefined,
  theme: {
    basePath: '',
    bootstrapVersion: '',
    is1d: false,
    logoutCallback: '',
    skin: 'default',
    skinName: 'default',
    skins: [],
    themeName: 'default',
    themeUrl: '',
    npmTheme: undefined,
  },
};
